### ISSUE TITLE
s-vals broken in 1.10.0

### ISSUE THREAD

**Issue by msmith7904** [putyourlightson/craft-sprig#176]
### Describe the bug
After upgrading to 1.10.0 s-vals is causing mergeJsonAttributes errors, hopefully attached screenshot is relevant.

Example code:
`<button s-vals="{{ { query: '' }|json_encode }}"></button>`

### Screenshots
![Screen Shot 2021-10-19 at 5 27 13 PM](https://user-images.githubusercontent.com/8161708/137994178-2cd5cb00-7c6f-41fa-9fdb-c75492246888.png)

### Versions
- Plugin version: 1.10.0
- Craft version: 3.7.13

**Comment by bencroker** [comment]
Thanks! Fixed in https://github.com/putyourlightson/craft-sprig-core/commit/40bb635317e00d6f6be637c15ed69df77db349c1 and released in version 1.10.1.

**Comment by stevendierick** [comment]
I'm having a similar issue in 1.10.1 when using Sprig to change the quantity of a product before adding it to the shopping cart.

The component is included when looping over the variants.

variants.twig

```
{% for item in product.variants %}
    {{ sprig('_partials/product/quantity', { index: loop.index, variant: item.id }) }}
{% endfor %}
```

quantity.twig

```
{% set index  = index ?? 0 %}
{% set variant  = craft.variants.id(variant).one() ?? null %}
{% set quantity = quantity ?? 0 %}

<div class="Quantity">
    {{ hiddenInput('purchasables[' ~ index ~ '][id]', variant.id) }}
    {{ hiddenInput('purchasables[' ~ index ~ '][qty]', quantity) }}
    
    <button
        {% if quantity > 0 %}
            sprig
            s-vals="{{ { quantity: quantity - 1 }|json_encode }}"
        {% else %}
            disabled
        {% endif %}
        class="Quantity-button Quantity-button--minus"
        type="button"
    >
        &minus;
    </button>

    <span class="Quantity-amount">
        {{ quantity }}
    </span>

    <button
        sprig
        s-vals="{{ { quantity: quantity + 1 }|json_encode }}"
        class="Quantity-button Quantity-button--plus"
        type="button"
    >
        &plus;
    </button>
</div>
```

Screenshot of the error: https://cln.sh/pl7h52rMzQ3vyYC9swWu

**Comment by bencroker** [comment]
I'm unable to replicate the error @stevendierick, can you please double check that Sprig 1.10.1 is installed?

**Comment by stevendierick** [comment]
Hey @bencroker, Sprig 1.10.1 was installed with Craft version 3.7.17. I also just updated to Sprig 1.10.2 and Craft 3.7.17.1 and the issue persists.

Edit:

I've tried to move a couple of things around and have found why my version isn't working anymore, and it might be because I'm using nested Sprig components.

detail.twig:

```
{% if currentUser and product.variants|length %}
    {{ sprig('_partials/product/variants', { product: product.id }) }}
{% endif %}
```

variants.twig

```
{% set product = craft.products.id(product).one() ?? null %}

<form sprig s-method="post" s-action="commerce/cart/update-cart">
    {% for item in product.variants %}
        {{ sprig('_partials/product/quantity', { index: loop.index, variant: item.id }) }}
    {% endfor %}

    <button class="Button Button--primary" type="submit">
        Add to basket
    </button>
</form>
```

quantity.twig

```
{% set index = index ?? 0 %}
{% set variant = craft.variants.id(variant).one() ?? null %}
{% set quantity = quantity ?? 0 %}

<div class="Quantity">
    {{ hiddenInput('purchasables[' ~ index ~ '][id]', variant.id) }}
    {{ hiddenInput('purchasables[' ~ index ~ '][qty]', quantity) }}
    
    <button
        {% if quantity > 0 %}
            sprig
            s-vals="{{ { quantity: quantity - 1 }|json_encode }}"
        {% else %}
            disabled
        {% endif %}
        class="Quantity-button Quantity-button--minus"
        type="button"
    >
        &minus;
    </button>

    <span class="Quantity-amount">
        {{ quantity }}
    </span>

    <button
        sprig
        s-vals="{{ { quantity: quantity + 1 }|json_encode }}"
        class="Quantity-button Quantity-button--plus"
        type="button"
    >
        &plus;
    </button>
</div>
```

If I change the Sprig include in `detail.twig` to a Twig include then the quantity component works fine as it did in 1.0.9, but then I can no longer use Sprig to add the items to the shopping cart.

**Comment by bencroker** [comment]
Thanks for reporting this! It is a different issue, fixed in https://github.com/putyourlightson/craft-sprig-core/commit/d348e41ff5e4a1c97cfddb525dd76a03c983d17a and released in version 1.10.3.
